import { fileURLToPath, URL } from 'node:url';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import {
  COMPANY,
  DEFAULT_DESCRIPTION,
  DEFAULT_TITLE,
  DEVELOPER,
  OG_IMAGE,
  OG_IMAGE_HEIGHT,
  OG_IMAGE_TYPE,
  OG_IMAGE_WIDTH,
  SITE_NAME,
  SITE_URL,
} from './src/lib/seo.ts';

/**
 * Crawlers read three files that must agree on one origin: index.html's
 * canonical, robots.txt's sitemap line, and sitemap.xml's <loc>. Rather than
 * keep three copies of the domain in sync by hand, this plugin stamps them all
 * from SITE_URL in src/lib/seo.ts — the same constant the runtime head uses.
 *
 * robots.txt and sitemap.xml are generated rather than committed to public/ for
 * that reason: a stale committed copy pointing at the old domain is the classic
 * way to de-index a site after a move.
 */
function seo(): Plugin {
  const generated: Record<string, () => string> = {
    '/robots.txt': robotsTxt,
    '/sitemap.xml': sitemapXml,
  };

  return {
    name: 'kudolane-seo',

    // 'pre' so the tokens are gone before Vite's own %ENV% pass looks at the HTML.
    transformIndexHtml: {
      order: 'pre',
      handler: fillTokens,
    },

    // `npm run dev` serves them too, so you can check them before deploying.
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const path = (req.url ?? '').split('?')[0];
        const build = generated[path];
        if (!build) return next();

        res.setHeader(
          'Content-Type',
          path.endsWith('.xml') ? 'application/xml; charset=utf-8' : 'text/plain; charset=utf-8',
        );
        res.end(build());
      });
    },

    generateBundle() {
      for (const [path, build] of Object.entries(generated)) {
        this.emitFile({ type: 'asset', fileName: path.slice(1), source: build() });
      }
    },
  };
}

/**
 * The values index.html asks for by name. Every one of them lives in
 * src/lib/seo.ts, so the head, the runtime hook and the generated files can
 * never disagree — and swapping the SVG social card for a PNG is one edit
 * there rather than four here.
 */
const TOKENS: Record<string, string> = {
  '%SITE_URL%': SITE_URL,
  '%SITE_NAME%': SITE_NAME,
  '%SITE_TITLE%': DEFAULT_TITLE,
  '%SITE_DESCRIPTION%': DEFAULT_DESCRIPTION,
  '%COMPANY%': COMPANY,
  '%AUTHOR%': DEVELOPER,
  '%OG_IMAGE%': OG_IMAGE,
  '%OG_IMAGE_TYPE%': OG_IMAGE_TYPE,
  '%OG_IMAGE_WIDTH%': OG_IMAGE_WIDTH,
  '%OG_IMAGE_HEIGHT%': OG_IMAGE_HEIGHT,
};

const escapeHtml = (value: string) =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/** Escapes for the inside of an existing pair of JSON quotes. */
const escapeJson = (value: string) => JSON.stringify(value).slice(1, -1);

const substitute = (text: string, escape: (value: string) => string) =>
  Object.entries(TOKENS).reduce((acc, [token, value]) => acc.split(token).join(escape(value)), text);

const LD_BLOCK = /(<script type="application\/ld\+json">)([\s\S]*?)(<\/script>)/g;

/**
 * Substitutes with the escaping the surrounding syntax actually needs.
 *
 * This matters more than it looks: the default title carries an ampersand,
 * which must be `&amp;` in markup but must stay a bare `&` inside a JSON-LD
 * script, where the contents are raw text rather than parsed HTML. One blanket
 * escape would corrupt one context or the other.
 */
function fillTokens(html: string): string {
  let out = '';
  let cursor = 0;

  for (const match of html.matchAll(LD_BLOCK)) {
    const start = match.index ?? 0;
    out += substitute(html.slice(cursor, start), escapeHtml);
    out += match[1] + substitute(match[2], escapeJson) + match[3];
    cursor = start + match[0].length;
  }

  return out + substitute(html.slice(cursor), escapeHtml);
}

/**
 * Crawling is deliberately wide open, including the AI and answer-engine bots.
 * `User-agent: *` already permits them; they are named anyway because several
 * (Google-Extended, Applebot-Extended) are consulted *only* by name, and
 * because an explicit list documents the intent for whoever edits this next.
 */
function robotsTxt(): string {
  const aiCrawlers = [
    'GPTBot',
    'OAI-SearchBot',
    'ChatGPT-User',
    'ClaudeBot',
    'Claude-User',
    'Claude-SearchBot',
    'anthropic-ai',
    'PerplexityBot',
    'Perplexity-User',
    'Google-Extended',
    'Applebot',
    'Applebot-Extended',
    'CCBot',
    'Amazonbot',
    'meta-externalagent',
    'Bytespider',
    'YouBot',
    'DuckAssistBot',
    'cohere-ai',
  ];

  return [
    `# ${SITE_NAME} — robots.txt (generated by vite.config.ts from src/lib/seo.ts)`,
    '# Everything here is public reference material. Crawl all of it.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    '# Search and AI crawlers, named explicitly so nothing is left to a default.',
    ...aiCrawlers.flatMap((agent) => [`User-agent: ${agent}`, 'Allow: /', '']),
    `Sitemap: ${SITE_URL}/sitemap.xml`,
    '',
  ].join('\n');
}

/**
 * One entry, and that is correct rather than lazy. The lab is a single URL —
 * the 29 design write-ups live behind `#/design/<id>`, and a URL fragment is
 * never a separate document to a crawler. Listing them would submit 29 copies
 * of the same <loc> and earn a "duplicate URL" notice in Search Console.
 *
 * If the router ever moves to real paths, generate the entries from
 * src/data/designs.ts here.
 */
function sitemapXml(): string {
  const lastmod = new Date().toISOString().slice(0, 10);

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    '  <url>',
    `    <loc>${SITE_URL}/</loc>`,
    `    <lastmod>${lastmod}</lastmod>`,
    '    <changefreq>weekly</changefreq>',
    '    <priority>1.0</priority>',
    '  </url>',
    '</urlset>',
    '',
  ].join('\n');
}

export default defineConfig({
  plugins: [react(), seo()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    port: 5173,
    // flip to true if you want `npm run dev` to pop the browser open
    open: false,
  },
});
